{
 "title": "Spring Boot Dashboard",
 "description": "Dashboard for Micrometer instrumented applications (Java, Spring Boot)",
 "tags": [
  "spring-boot",
  "micrometer",
  "prometheus"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "application", "label": "Application", "query": "label_values(application)" },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(jvm_memory_used_bytes{application=\"$application\"}, instance)"
   },
   {
    "name": "jvm_memory_pool_heap",
    "label": "Memory Pools Heap",
    "query": "label_values(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", area=\"heap\"},id)"
   },
   {
    "name": "jvm_memory_pool_nonheap",
    "label": "Memory Pools Non-Heap",
    "query": "label_values(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", area=\"nonheap\"},id)"
   },
   {
    "name": "hikaricp_pool_name",
    "label": "Hikari  Pool",
    "query": "label_values(hikaricp_connections_min{application=\"$application\", instance=~\"$instance\"}, pool)"
   },
   {
    "name": "jdbc_connection_name",
    "label": "JDBC Connection",
    "query": "label_values(jdbc_connections_min{application=\"$application\", instance=~\"$instance\"}, name)"
   }
  ]
 },
 "panels": [
  { "title": "Quick Facts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "process_uptime_seconds{application=\"$application\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "system_cpu_usage{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "system"
    },
    {
     "expr": "process_cpu_usage{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "process"
    },
    {
     "expr": "avg_over_time(process_cpu_usage{application=\"$application\", instance=\"$instance\"}[1h])",
     "legendFormat": "process-1h"
    }
   ]
  },
  {
   "title": "Heap used",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", area=\"heap\"})*100/sum(jvm_memory_max_bytes{application=\"$application\",instance=\"$instance\", area=\"heap\"})"
    }
   ]
  },
  {
   "title": "Non-Heap used",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", area=\"nonheap\"})*100/sum(jvm_memory_max_bytes{application=\"$application\",instance=\"$instance\", area=\"nonheap\"})"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "format": "dateTimeAsIso",
   "valueName": "current",
   "targets": [
    {
     "expr": "process_start_time_seconds{application=\"$application\", instance=\"$instance\"}*1000"
    }
   ]
  },
  { "title": "I/O Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\"}[1m]))",
     "legendFormat": "HTTP"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{application=\"$application\", instance=\"$instance\", status!~\"5..\"}[1m]))/sum(rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", status!~\"5..\"}[1m]))",
     "legendFormat": "HTTP - AVG"
    },
    {
     "expr": "max(http_server_requests_seconds_max{application=\"$application\", instance=\"$instance\", status!~\"5..\"})",
     "legendFormat": "HTTP - MAX"
    }
   ]
  },
  {
   "title": "Utilisation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tomcat_threads_busy{application=\"$application\", instance=\"$instance\"} or tomcat_threads_busy_threads{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "TOMCAT - BSY"
    },
    {
     "expr": "tomcat_threads_current{application=\"$application\", instance=\"$instance\"} or tomcat_threads_current_threads{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "TOMCAT - CUR"
    },
    {
     "expr": "tomcat_threads_config_max{application=\"$application\", instance=\"$instance\"} or tomcat_threads_config_max_threads{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "TOMCAT - MAX"
    },
    {
     "expr": "jetty_threads_busy{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "JETTY - BSY"
    },
    {
     "expr": "jetty_threads_current{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "JETTY - CUR"
    },
    {
     "expr": "jetty_threads_config_max{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "JETTY - MAX"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 8 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", status=~\"5..\"}[1m]))",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Hikari Connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Max",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 16 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "hikaricp_connections_max{application=\"$application\", instance=~\"$instance\", pool=~\"$hikaricp_pool_name\"}"
      }
     ]
    },
    {
     "title": "Connections",
     "type": "graph",
     "gridPos": { "h": 10, "w": 20, "x": 4, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "hikaricp_connections_idle{application=\"$application\", instance=~\"$instance\", pool=~\"$hikaricp_pool_name\"}",
       "legendFormat": "Idle"
      },
      {
       "expr": "hikaricp_connections_pending{application=\"$application\", instance=~\"$instance\", pool=~\"$hikaricp_pool_name\"}",
       "legendFormat": "Pending"
      },
      {
       "expr": "hikaricp_connections_active{application=\"$application\", instance=~\"$instance\", pool=~\"$hikaricp_pool_name\"}",
       "legendFormat": "Active"
      }
     ]
    },
    {
     "title": "Min",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 21 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "hikaricp_connections_min{application=\"$application\", instance=~\"$instance\", pool=~\"$hikaricp_pool_name\"}"
      }
     ]
    },
    {
     "title": "Usage Time",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "dtdurations" }
     ],
     "targets": [
      {
       "expr": "rate(hikaricp_connections_usage_seconds_sum{application=\"$application\", instance=~\"$instance\", pool=~\"$hikaricp_pool_name\"}[5m]) / rate(hikaricp_connections_usage_seconds_count{application=\"$application\", instance=~\"$instance\", pool=~\"$hikaricp_pool_name\"}[5m])",
       "legendFormat": "Usage"
      }
     ]
    },
    {
     "title": "Creation Time",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 26 },
     "yaxes": [
      { "format": "dtdurations" }
     ],
     "targets": [
      {
       "expr": "rate(hikaricp_connections_creation_seconds_sum{application=\"$application\", instance=~\"$instance\", pool=~\"$hikaricp_pool_name\"}[5m]) / rate(hikaricp_connections_creation_seconds_count{application=\"$application\", instance=~\"$instance\", pool=~\"$hikaricp_pool_name\"}[5m])",
       "legendFormat": "Creation"
      }
     ]
    },
    {
     "title": "Acquire Time",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 26 },
     "yaxes": [
      { "format": "dtdurations" }
     ],
     "targets": [
      {
       "expr": "rate(hikaricp_connections_acquire_seconds_sum{application=\"$application\", instance=~\"$instance\", pool=~\"$hikaricp_pool_name\"}[5m]) / rate(hikaricp_connections_acquire_seconds_count{application=\"$application\", instance=~\"$instance\", pool=~\"$hikaricp_pool_name\"}[5m])",
       "legendFormat": "Acquire"
      }
     ]
    }
   ]
  },
  {
   "title": "JDBC Connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Min",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 8, "x": 0, "y": 7 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "jdbc_connections_min{application=\"$application\", instance=~\"$instance\", name=~\"$jdbc_connection_name\"}"
      }
     ]
    },
    {
     "title": "Active",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 8, "x": 8, "y": 7 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "jdbc_connections_active{application=\"$application\", instance=~\"$instance\", name=~\"$jdbc_connection_name\"}"
      }
     ]
    },
    {
     "title": "Max",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 8, "x": 16, "y": 7 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "jdbc_connections_max{application=\"$application\", instance=~\"$instance\", name=~\"$jdbc_connection_name\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "JVM Heap",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", area=\"heap\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum(jvm_memory_committed_bytes{application=\"$application\", instance=\"$instance\", area=\"heap\"})",
       "legendFormat": "committed"
      },
      {
       "expr": "sum(jvm_memory_max_bytes{application=\"$application\", instance=\"$instance\", area=\"heap\"})",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "JVM Non-Heap",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 18 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", area=\"nonheap\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum(jvm_memory_committed_bytes{application=\"$application\", instance=\"$instance\", area=\"nonheap\"})",
       "legendFormat": "committed"
      },
      {
       "expr": "sum(jvm_memory_max_bytes{application=\"$application\", instance=\"$instance\", area=\"nonheap\"})",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "JVM Total",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum(jvm_memory_committed_bytes{application=\"$application\", instance=\"$instance\"})",
       "legendFormat": "committed"
      },
      {
       "expr": "sum(jvm_memory_max_bytes{application=\"$application\", instance=\"$instance\"})",
       "legendFormat": "max"
      },
      {
       "expr": "process_memory_rss_bytes{application=\"$application\", instance=\"$instance\"}",
       "legendFormat": "rss"
      },
      {
       "expr": "process_memory_pss_bytes{application=\"$application\", instance=\"$instance\"}",
       "legendFormat": "pss"
      },
      {
       "expr": "process_memory_swap_bytes{application=\"$application\", instance=\"$instance\"}",
       "legendFormat": "swap"
      },
      {
       "expr": "process_memory_swappss_bytes{application=\"$application\", instance=\"$instance\"}",
       "legendFormat": "swappss"
      },
      {
       "expr": "process_memory_pss_bytes{application=\"$application\", instance=\"$instance\"} + process_memory_swap_bytes{application=\"$application\", instance=\"$instance\"}",
       "legendFormat": "phys (pss+swap)"
      }
     ]
    },
    {
     "title": "JVM Native Memory",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 18 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "(process_memory_pss_bytes{application=\"$application\", instance=\"$instance\"} + process_memory_swap_bytes{application=\"$application\", instance=\"$instance\"}  - on(application,instance) sum(jvm_memory_committed_bytes{application=\"$application\", instance=\"$instance\"})  by(application,instance)) >= 0",
       "legendFormat": "native"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Misc",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Thread States",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_threads_states_threads{application=\"$application\", instance=\"$instance\"}",
       "legendFormat": "{{state}}"
      }
     ]
    },
    {
     "title": "Load",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "system_load_average_1m{application=\"$application\", instance=\"$instance\"}",
       "legendFormat": "system-1m"
      },
      {},
      {
       "expr": "system_cpu_count{application=\"$application\", instance=\"$instance\"}",
       "legendFormat": "cpu"
      }
     ]
    },
    {
     "title": "Threads",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_threads_live{application=\"$application\", instance=\"$instance\"} or jvm_threads_live_threads{application=\"$application\", instance=\"$instance\"}",
       "legendFormat": "live"
      },
      {
       "expr": "jvm_threads_daemon{application=\"$application\", instance=\"$instance\"} or jvm_threads_daemon_threads{application=\"$application\", instance=\"$instance\"}",
       "legendFormat": "daemon"
      },
      {
       "expr": "jvm_threads_peak{application=\"$application\", instance=\"$instance\"} or jvm_threads_peak_threads{application=\"$application\", instance=\"$instance\"}",
       "legendFormat": "peak"
      },
      {
       "expr": "process_threads{application=\"$application\", instance=\"$instance\"}",
       "legendFormat": "process"
      }
     ]
    },
    {
     "title": "File Descriptors",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "process_open_fds{application=\"$application\", instance=\"$instance\"}",
       "legendFormat": "open"
      },
      {
       "expr": "process_max_fds{application=\"$application\", instance=\"$instance\"}",
       "legendFormat": "max"
      },
      {
       "expr": "process_files_open{application=\"$application\", instance=\"$instance\"} or process_files_open_files{application=\"$application\", instance=\"$instance\"}",
       "legendFormat": "open"
      },
      {
       "expr": "process_files_max{application=\"$application\", instance=\"$instance\"} or process_files_max_files{application=\"$application\", instance=\"$instance\"}",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "Log Events (1m)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(logback_events_total{application=\"$application\", instance=\"$instance\"}[1m])",
       "legendFormat": "{{level}}"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Memory Pools (Heap)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "repeat": "persistence_counts",
   "collapsed": true,
   "panels": [
    {
     "title": "$jvm_memory_pool_heap",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 6 },
     "repeat": "jvm_memory_pool_heap",
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", id=\"$jvm_memory_pool_heap\"}",
       "legendFormat": "used"
      },
      {
       "expr": "jvm_memory_committed_bytes{application=\"$application\", instance=\"$instance\", id=\"$jvm_memory_pool_heap\"}",
       "legendFormat": "commited"
      },
      {
       "expr": "jvm_memory_max_bytes{application=\"$application\", instance=\"$instance\", id=\"$jvm_memory_pool_heap\"}",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "$jvm_memory_pool_heap",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 6 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", id=\"$jvm_memory_pool_heap\"}",
       "legendFormat": "used"
      },
      {
       "expr": "jvm_memory_committed_bytes{application=\"$application\", instance=\"$instance\", id=\"$jvm_memory_pool_heap\"}",
       "legendFormat": "commited"
      },
      {
       "expr": "jvm_memory_max_bytes{application=\"$application\", instance=\"$instance\", id=\"$jvm_memory_pool_heap\"}",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "$jvm_memory_pool_heap",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 6 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", id=\"$jvm_memory_pool_heap\"}",
       "legendFormat": "used"
      },
      {
       "expr": "jvm_memory_committed_bytes{application=\"$application\", instance=\"$instance\", id=\"$jvm_memory_pool_heap\"}",
       "legendFormat": "commited"
      },
      {
       "expr": "jvm_memory_max_bytes{application=\"$application\", instance=\"$instance\", id=\"$jvm_memory_pool_heap\"}",
       "legendFormat": "max"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Memory Pools (Non-Heap)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "$jvm_memory_pool_nonheap",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 11 },
     "repeat": "jvm_memory_pool_nonheap",
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", id=\"$jvm_memory_pool_nonheap\"}",
       "legendFormat": "used"
      },
      {
       "expr": "jvm_memory_committed_bytes{application=\"$application\", instance=\"$instance\", id=\"$jvm_memory_pool_nonheap\"}",
       "legendFormat": "commited"
      },
      {
       "expr": "jvm_memory_max_bytes{application=\"$application\", instance=\"$instance\", id=\"$jvm_memory_pool_nonheap\"}",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "$jvm_memory_pool_nonheap",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 11 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", id=\"$jvm_memory_pool_nonheap\"}",
       "legendFormat": "used"
      },
      {
       "expr": "jvm_memory_committed_bytes{application=\"$application\", instance=\"$instance\", id=\"$jvm_memory_pool_nonheap\"}",
       "legendFormat": "commited"
      },
      {
       "expr": "jvm_memory_max_bytes{application=\"$application\", instance=\"$instance\", id=\"$jvm_memory_pool_nonheap\"}",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "$jvm_memory_pool_nonheap",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 11 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", id=\"$jvm_memory_pool_nonheap\"}",
       "legendFormat": "used"
      },
      {
       "expr": "jvm_memory_committed_bytes{application=\"$application\", instance=\"$instance\", id=\"$jvm_memory_pool_nonheap\"}",
       "legendFormat": "commited"
      },
      {
       "expr": "jvm_memory_max_bytes{application=\"$application\", instance=\"$instance\", id=\"$jvm_memory_pool_nonheap\"}",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "$jvm_memory_pool_nonheap",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", id=\"$jvm_memory_pool_nonheap\"}",
       "legendFormat": "used"
      },
      {
       "expr": "jvm_memory_committed_bytes{application=\"$application\", instance=\"$instance\", id=\"$jvm_memory_pool_nonheap\"}",
       "legendFormat": "commited"
      },
      {
       "expr": "jvm_memory_max_bytes{application=\"$application\", instance=\"$instance\", id=\"$jvm_memory_pool_nonheap\"}",
       "legendFormat": "max"
      }
     ]
    }
   ]
  },
  {
   "title": "Garbage Collection",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Collections",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "rate(jvm_gc_pause_seconds_count{application=\"$application\", instance=\"$instance\"}[1m])",
       "legendFormat": "{{action}} ({{cause}})"
      }
     ]
    },
    {
     "title": "Pause Durations",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 12 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(jvm_gc_pause_seconds_sum{application=\"$application\", instance=\"$instance\"}[1m])/rate(jvm_gc_pause_seconds_count{application=\"$application\", instance=\"$instance\"}[1m])",
       "legendFormat": "avg {{action}} ({{cause}})"
      },
      {
       "expr": "jvm_gc_pause_seconds_max{application=\"$application\", instance=\"$instance\"}",
       "legendFormat": "max {{action}} ({{cause}})"
      }
     ]
    },
    {
     "title": "Allocated/Promoted",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 12 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "rate(jvm_gc_memory_allocated_bytes_total{application=\"$application\", instance=\"$instance\"}[1m])",
       "legendFormat": "allocated"
      },
      {
       "expr": "rate(jvm_gc_memory_promoted_bytes_total{application=\"$application\", instance=\"$instance\"}[1m])",
       "legendFormat": "promoted"
      }
     ]
    }
   ]
  },
  {
   "title": "Classloading",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Classes loaded",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_classes_loaded{application=\"$application\", instance=\"$instance\"} or jvm_classes_loaded_classes{application=\"$application\", instance=\"$instance\"}",
       "legendFormat": "loaded"
      }
     ]
    },
    {
     "title": "Class delta (5m)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "delta(jvm_classes_loaded{application=\"$application\",instance=\"$instance\"}[5m]) or delta(jvm_classes_loaded_classes{application=\"$application\",instance=\"$instance\"}[5m])",
       "legendFormat": "delta"
      }
     ]
    }
   ]
  },
  {
   "title": "Buffer Pools",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Direct Buffers",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_buffer_memory_used_bytes{application=\"$application\", instance=\"$instance\", id=\"direct\"}",
       "legendFormat": "used"
      },
      {
       "expr": "jvm_buffer_total_capacity_bytes{application=\"$application\", instance=\"$instance\", id=\"direct\"}",
       "legendFormat": "capacity"
      }
     ]
    },
    {
     "title": "Direct Buffers",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_buffer_count{application=\"$application\", instance=\"$instance\", id=\"direct\"} or jvm_buffer_count_buffers{application=\"$application\", instance=\"$instance\", id=\"direct\"}",
       "legendFormat": "count"
      }
     ]
    },
    {
     "title": "Mapped Buffers",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 28 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_buffer_memory_used_bytes{application=\"$application\", instance=\"$instance\", id=\"mapped\"}",
       "legendFormat": "used"
      },
      {
       "expr": "jvm_buffer_total_capacity_bytes{application=\"$application\", instance=\"$instance\", id=\"mapped\"}",
       "legendFormat": "capacity"
      }
     ]
    },
    {
     "title": "Mapped Buffers",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_buffer_count{application=\"$application\", instance=\"$instance\", id=\"mapped\"} or jvm_buffer_count_buffers{application=\"$application\", instance=\"$instance\", id=\"mapped\"}",
       "legendFormat": "count"
      }
     ]
    }
   ]
  }
 ]
}