server:
  session:
    timeout: 20

security:
  user:
    name: admin
    password: admin

management:
  context-path: /manage
  security:
    enabled: false

spring:
  h2:
    console:
      enabled: true