#docinquest:
#  ribbon:
#    listOfServers: localhost:8107
eureka:
  client:
    enabled: true
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
#stos:
#  ribbon:
#    listOfServers: localhost:9090
tracer:
  retry:
    delay: 500
    max-attempts: 6
spring:
  application:
    name: retry
